name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build tools
      run: sudo apt-get install build-essential libcunit1 libcunit1-dev

    - name: Build
      run: gcc -o cal functions.h functions.c tests.c -lcunit

    - name: Run tests
      run: ./cal