name: C Build Test Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  install:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install build tools
      run: sudo apt-get install build-essential libcunit1 libcunit1-dev libc6-dev gcc-multilib cppcheck

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Build
      run: gcc -o cal functions.h functions.c tests.h tests.c -lcunit

  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run tests
      run: |
        echo "Running tests..."
        ./cal
        echo "Exit code: $?"  # This will print the exit code of the last command
      continue-on-error: false  # This is the default, but it's good to be explicit
