name: C Build Test Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List src directory contents
      run: ls -la $GITHUB_WORKSPACE

  install:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Install build tools
      run: sudo apt-get install build-essential libcunit1 libcunit1-dev libc6-dev gcc-multilib cppcheck

  build:
    runs-on: ubuntu-latest
    needs: install    
    steps:
    
    - name: List src directory contents
      run: ls -la $GITHUB_WORKSPACE
      
    - name: Build
      run: gcc -o cal -Iinclude $GITHUB_WORKSPACE/functions.c $GITHUB_WORKSPACE/tests.c -lcunit

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run tests
      run: |
        echo "Running tests..."
        ./cal
        echo "Exit code: $?"  # This will print the exit code of the last command
      continue-on-error: false  # This is the default, but it's good to be explicit
