name: C Build Test Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout-install-build-test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get install build-essential libcunit1 libcunit1-dev libc6-dev gcc-multilib cppcheck

    - name: Build
      run: gcc -o cal functions.h functions.c tests.h tests.c -lcunit

    - name: Run tests
      run: |
        echo "Running tests..."
        ./cal
        echo "Exit code: $?"  # This will print the exit code of the last command
      continue-on-error: false  # This is the default, but it's good to be explicit
