name: C Build Test (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cunit

    - name: Add MSYS2 to PATH
      run: echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
      shell: powershell

    - name: Set up environment variables
      run: |
        [Environment]::SetEnvironmentVariable('C_INCLUDE_PATH', 'C:/tools/msys64/mingw64/include', 'Process')
        [Environment]::SetEnvironmentVariable('LIBRARY_PATH', 'C:/tools/msys64/mingw64/lib', 'Process')
      shell: powershell

    - name: Verify GCC Installation
      run: gcc --version
      shell: powershell

    - name: Build
      run: gcc -o cal.exe functions.c tests.c -I/mingw64/include -L/mingw64/lib -lcunit
      shell: powershell

    - name: List files
      run: ls -la
      shell: powershell

    - name: Set execute permissions
      run: chmod +x cal.exe
      shell: powershell

    - name: Run tests
      run: ./cal.exe
      shell: powershell
