name: C Build Test Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MSYS2
      run: choco install msys2

    - name: Set up MSYS2 environment
      shell: powershell
      run: |
        $env:Path += ";C:/tools/msys64/usr/bin;C:/tools/msys64/mingw64/bin"
        C:/tools/msys64/usr/bin/bash -lc "pacman -Syu --noconfirm"
        C:/tools/msys64/usr/bin/bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-cunit"
        
    - name: Verify CUnit installation
      shell: powershell
      run: |
        & 'C:/tools/msys64/usr/bin/bash.exe' -lc "pacman -Ql mingw-w64-x86_64-cunit"
        
    - name: Compile C code
      shell: bash
      run: |
        gcc -o cal.exe functions.c tests.c -I/mingw64/include/CUnit -L/mingw64/lib -lcunit

    - name: Run tests
      shell: bash
      run: |
        ./cal.exe
