name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add GCC to PATH
      run: |
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH
        
    - name: Verify GCC installation
      run: gcc --version

    - name: Compile
      run: gcc -o cal.exe functions.c tests.c -I"C:/msys64/mingw64/include" -lcunit

    - name: Run tests
      run: ./cal.exe
