name: C Build Test Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools
      run: |
        choco install make
        choco install gcc
        choco install cunit

    - name: Run Code Quality Check
      run: |
        echo "Running code quality check..."
        cppcheck --check-config --enable=all --inconclusive -i tests.c .  # Ignore tests.c
      continue-on-error: true  # Allow the build to continue even if cppcheck finds issues

    - name: Build
      run: gcc -o cal functions.h functions.c tests.c -lcunit

    - name: Run tests
      run: |
        echo "Running tests..."
        ./cal
        echo "Exit code: $?"  # This will print the exit code of the last command
      continue-on-error: false  # This is the default, but it's good to be explicit
