name: C Build Test Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MSYS2
      run: |
        choco install msys2
        refreshenv

    - name: Set up MSYS2
      shell: msys2 {0}
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-cunit

    - name: Compile C code
      shell: msys2 {0}
      run: |
        gcc -o cal.exe functions.c tests.c -I/mingw64/include -L/mingw64/lib -lcunit

    - name: Run tests
      shell: msys2 {0}
      run: |
        ./cal.exe
