name: C Build Test (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add MSYS2 to PATH
      run: echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
      shell: msys2

    - name: Set up environment variables
      run: |
        echo "export C_INCLUDE_PATH=/mingw64/include" >> $GITHUB_ENV
        echo "export LIBRARY_PATH=/mingw64/lib" >> $GITHUB_ENV
      shell: msys2

    - name: Verify GCC Installation
      run: gcc --version
      shell: msys2

    - name: Build
      run: gcc -o cal.exe functions.c tests.c -I/mingw64/include -L/mingw64/lib -lcunit
      shell: msys2

    - name: List files
      run: ls -la
      shell: msys2

    - name: Set execute permissions
      run: chmod +x cal.exe
      shell: msys2

    - name: Run tests
      run: ./cal.exe
      shell: msys2
