name: C Build Test Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MSYS2
      run: choco install msys2

    - name: Set up MSYS2 environment
      shell: powershell
      run: |
        $env:Path += ";C:/tools/msys64/usr/bin;C:/tools/msys64/mingw64/bin"
        C:/tools/msys64/usr/bin/bash -lc "pacman -Syu --noconfirm"
        C:/tools/msys64/usr/bin/bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-cunit"
        
    - name: Verify CUnit installation
      shell: powershell
      run: |
        & 'C:/tools/msys64/usr/bin/bash.exe' -lc "pacman -Ql mingw-w64-x86_64-cunit"

    - name: Set up environment variables
      run: |
        echo "C_INCLUDE_PATH=/mingw64/include" >> $GITHUB_ENV
        echo "LIBRARY_PATH=/mingw64/lib" >> $GITHUB_ENV
        
     - name: Add MSYS2 to PATH
      run: echo "C:/tools/msys64/usr/bin" >> $GITHUB_PATH
      
    - name: Compile C code
      shell: msys2 {0}
      run: gcc -o cal.exe functions.c tests.c -I/C:/tools/msys64/mingw64/include -L/C:/tools/msys64/mingw64/lib -lcunit

    - name: Run tests
      shell: msys2 {0}
      run: ./cal.exe
