name: C Build Test Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v3
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cunit

    - name: Compile C code
      run: |
        gcc -o cal.exe functions.h functions.c tests.c -lcunit

    - name: Run tests
      run: |
        ./cal.exe
